server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: wallet-core

  datasource:
    # url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:digital_wallet}
    # username: ${DB_USERNAME:wallet_user}
    # password: ${DB_PASSWORD:wallet_password}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      # host: ${REDIS_HOST: localhost}
      # port: ${REDIS_PORT: 6379}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

jwt:
  # secret: ${JWT_SECRET:default_secret_key}
  # access-token-expiry: 3600000
  # refresh-token-expiry: 604800000
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  endpoint: ${MOMO_ENDPOINT}
  redirect-url: ${MOMO_REDIRECT_URL}
  ipn-url: ${MOMO_IPN_URL}
