package com.digitalwallet.domain.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_PROFILE_UPDATED,
    PASSWORD_CHANGED,
    EMAIL_VERIFIED,
    DEPOSIT_COMPLETED,
    WITHDRAW_REQUESTED,
    TRANSFER_COMPLETED,
    WALLET_FROZEN,
    WALLET_SUSPENDED
}
